version: '3.9'
services:
  postgresql:
    image: postgres:12
    container_name: postgresLaborEE
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: laboree
    ports:
      - "5434:5432"
    volumes:
      - ./data:/var/lib/postgresql/data